apiVersion: v1
kind: Pod
metadata:
  name: akstest
  labels:
    app: bootstrap
spec:
  containers:
  - name: akstest
    image: gchandru1977/springboot
    tag: 333
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: $KUBERNETES_SECRET_NAME
---
# This is the service
apiVersion: v1
kind: Service
metadata:
  name: mastersvc
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: bootstrap